# Generated by Django 5.0.6 on 2026-05-12 04:30

import apps.accounts.managers
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyuser',
            options={'default_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='agencyuser',
            managers=[
                ('objects', apps.accounts.managers.AgencyUserManager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
