# Generated by Django 5.0.6 on 2026-05-12 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('validity_months', models.PositiveIntegerField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_on', models.DateField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('EXPIRING', 'Expiring'), ('EXPIRED', 'Expired')], default='VALID', max_length=16)),
                ('certificate_reference', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='drivers.driver')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='training.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['agency'], name='training_co_agency__a04f44_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('agency', 'name'), name='course_unique_name_per_agency'),
        ),
        migrations.AddIndex(
            model_name='completion',
            index=models.Index(fields=['agency'], name='training_co_agency__7ca221_idx'),
        ),
        migrations.AddIndex(
            model_name='completion',
            index=models.Index(fields=['agency', 'status', 'expires_on'], name='training_co_agency__367d2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='completion',
            constraint=models.UniqueConstraint(fields=('agency', 'driver', 'course'), name='completion_unique_per_driver_course'),
        ),
    ]
