# Generated by Django 5.0.6 on 2026-05-12 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('DRIVING_LICENCE', 'Driving Licence'), ('RIGHT_TO_WORK', 'Right To Work'), ('INSURANCE', 'Insurance'), ('MOT', 'Mot'), ('DBS', 'Dbs'), ('CPC', 'Cpc')], max_length=32)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('EXPIRING', 'Expiring'), ('EXPIRED', 'Expired'), ('MISSING', 'Missing')], default='MISSING', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driver')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['agency'], name='documents_d_agency__f28af0_idx'), models.Index(fields=['agency', 'status', 'expires_on'], name='documents_d_agency__9d35eb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='driverdocument',
            constraint=models.UniqueConstraint(fields=('agency', 'driver', 'kind'), name='document_unique_kind_per_driver'),
        ),
    ]
