# Generated by Django 5.0.6 on 2026-05-17 20:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('drivers', '0001_initial'),
        ('invoicing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_holder_name', models.CharField(max_length=120)),
                ('sort_code', models.CharField(max_length=8)),
                ('account_number', models.CharField(max_length=12)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cop_status', models.CharField(blank=True, default='', max_length=16)),
                ('cop_checked_at', models.DateTimeField(blank=True, null=True)),
                ('provider_beneficiary_id', models.CharField(blank=True, default='', max_length=64)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='drivers.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_batch_id', models.CharField(blank=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=64)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payruns_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payruns_created', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payruns_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayRunItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, default='', max_length=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('RETURNED', 'Returned')], default='PENDING', max_length=16)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=64)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payrun_items', to='payments.driverbankaccount')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrun_items', to='drivers.driver')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrun_items', to='invoicing.invoice')),
                ('payrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.payrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=64)),
                ('provider_event_id', models.CharField(blank=True, default='', max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
                ('payrun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.payrun')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.payrunitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgencyPaymentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('MODULR', 'Modulr')], default='MODULR', max_length=16)),
                ('provider_customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('provider_account_id', models.CharField(max_length=64)),
                ('sort_code', models.CharField(blank=True, default='', max_length=8)),
                ('account_number', models.CharField(blank=True, default='', max_length=12)),
                ('account_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_known_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('last_balance_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['agency'], name='payments_ag_agency__fef457_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='agencypaymentaccount',
            constraint=models.UniqueConstraint(fields=('agency', 'provider'), name='payment_account_one_per_provider_per_agency'),
        ),
        migrations.AddIndex(
            model_name='driverbankaccount',
            index=models.Index(fields=['agency'], name='payments_dr_agency__d1729e_idx'),
        ),
        migrations.AddIndex(
            model_name='driverbankaccount',
            index=models.Index(fields=['agency', 'driver', 'is_primary'], name='payments_dr_agency__2df425_idx'),
        ),
        migrations.AddIndex(
            model_name='payrun',
            index=models.Index(fields=['agency'], name='payments_pa_agency__bc0fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='payrun',
            index=models.Index(fields=['agency', 'status', 'period_end'], name='payments_pa_agency__a17629_idx'),
        ),
        migrations.AddIndex(
            model_name='payrunitem',
            index=models.Index(fields=['agency'], name='payments_pa_agency__03e26b_idx'),
        ),
        migrations.AddIndex(
            model_name='payrunitem',
            index=models.Index(fields=['agency', 'payrun', 'status'], name='payments_pa_agency__1268b5_idx'),
        ),
        migrations.AddIndex(
            model_name='payrunitem',
            index=models.Index(fields=['agency', 'provider_payment_id'], name='payments_pa_agency__8ceb27_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentstatusevent',
            index=models.Index(fields=['agency'], name='payments_pa_agency__6b3230_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentstatusevent',
            index=models.Index(fields=['agency', 'event_type', 'created_at'], name='payments_pa_agency__2be8c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentstatusevent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id__gt', '')), fields=('agency', 'provider_event_id'), name='payment_event_unique_per_agency'),
        ),
    ]
