# Generated by Django 5.0.6 on 2026-05-24 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.CharField(blank=True, default='', max_length=16)),
                ('make', models.CharField(blank=True, default='', max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, default='', max_length=32)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='drivers.driver')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['agency'], name='vehicles_ve_agency__95a500_idx')],
            },
        ),
    ]
