# Generated by Django 5.0.6 on 2026-05-11 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('timezone', models.CharField(default='Europe/London', max_length=64)),
                ('primary_color', models.CharField(default='#004B44', max_length=9)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agencies/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['agency'], name='agencies_de_agency__0aba8a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='depot',
            constraint=models.UniqueConstraint(fields=('agency', 'name'), name='depot_unique_name_per_agency'),
        ),
    ]
