# Generated by Django 5.0.6 on 2026-05-11 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_applications', to=settings.AUTH_USER_MODEL)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='drivers.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('LICENCE', 'Licence'), ('PASSPORT', 'Passport'), ('RTW_EVIDENCE', 'Rtw Evidence')], max_length=32)),
                ('file', models.FileField(upload_to='applications/%Y/%m/')),
                ('ocr_payload', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onboarding.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('PERSONAL_DETAILS', 'Personal Details'), ('DOCUMENT_UPLOAD', 'Document Upload'), ('OCR', 'Ocr'), ('DVLA_CHECK', 'Dvla Check'), ('RTW_CHECK', 'Rtw Check'), ('CONTRACT_SIGNATURE', 'Contract Signature')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('outcome', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='onboarding.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['agency'], name='onboarding__agency__13207a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['agency', 'state'], name='onboarding__agency__808603_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationdocument',
            index=models.Index(fields=['agency'], name='onboarding__agency__965e60_idx'),
        ),
        migrations.AddIndex(
            model_name='step',
            index=models.Index(fields=['agency'], name='onboarding__agency__4bf8f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('application', 'kind'), name='step_unique_kind_per_application'),
        ),
    ]
