# Generated by Django 5.0.6 on 2026-05-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='kind',
            field=models.CharField(choices=[('LICENCE', 'Licence'), ('PASSPORT', 'Passport'), ('RTW_EVIDENCE', 'Rtw Evidence'), ('PHV_LICENCE', 'Phv Licence'), ('INSURANCE', 'Insurance')], max_length=32),
        ),
    ]
