# Generated by Django 5.0.6 on 2026-05-11 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('ni_number', models.CharField(blank=True, default='', max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('RESTING', 'Resting'), ('SUSPENDED', 'Suspended'), ('OFFBOARDED', 'Offboarded')], default='PENDING', max_length=16)),
                ('licence_type', models.CharField(blank=True, choices=[('B', 'B'), ('C1', 'C1'), ('C', 'C'), ('D1', 'D1'), ('D', 'D')], default='', max_length=8)),
                ('flex_enrolled', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True, default='')),
                ('offboard_reason', models.TextField(blank=True, default='')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='agencies.depot')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_notes', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='drivers.driver')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['agency'], name='drivers_dri_agency__db194d_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['agency', 'status'], name='drivers_dri_agency__90c8ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('agency', 'email'), name='driver_unique_email_per_agency'),
        ),
        migrations.AddIndex(
            model_name='drivernote',
            index=models.Index(fields=['agency'], name='drivers_dri_agency__d01fb3_idx'),
        ),
    ]
