# Generated by Django 5.0.6 on 2026-05-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='dbs_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='dbs_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
