# Generated by Django 5.0.6 on 2026-05-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_dbs_consent_driver_dbs_consent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='registration_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
