# Generated by Django 5.0.6 on 2026-05-12 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='scheduling.shift'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['agency'], name='invoicing_i_agency__b1c735_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['agency', 'status', 'period_end'], name='invoicing_i_agency__50e020_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('agency', 'number'), name='invoice_unique_number_per_agency'),
        ),
        migrations.AddIndex(
            model_name='invoicecounter',
            index=models.Index(fields=['agency'], name='invoicing_i_agency__0d4261_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicecounter',
            constraint=models.UniqueConstraint(fields=('agency', 'year'), name='invoice_counter_unique_per_year'),
        ),
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['agency'], name='invoicing_i_agency__81e94b_idx'),
        ),
    ]
